#os: linux
#
#dist: xenial
#
language: python

python:
#  - "3.6"
  - "3.7"
#  - "3.8"

cache: pip

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p "${HOME}/miniconda"
  - export PATH="${HOME}/miniconda/bin:${PATH}"

  - conda config --add channels conda-forge
#  - conda update --yes conda

install:
  - conda create --yes -n test python="$TRAVIS_PYTHON_VERSION"
  - source activate test

  - conda install --yes orekit=10.0

  - pip install codecov
  - pip install -e ".[test]" .

script: pytest

after_success: codecov
