os: linux

language: python

python:
# commented out not to exhaust Travis CI credits
#  - "3.6"
#  - "3.7"
#  - "3.8"
  - "3.9"

cache: pip

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O Miniconda3.sh
  - chmod +x Miniconda3.sh
  - ./Miniconda3.sh -b -p "${HOME}/miniconda3"
  - export PATH="${HOME}/miniconda3/bin:${PATH}"
  - export PYTHONPATH="$PYTHONPATH:$(pwd)"

  - conda config --set always_yes yes
  - conda config --add channels conda-forge
  - conda config --set channel_priority false
  - conda update conda


install:
  - conda create -n test python="$TRAVIS_PYTHON_VERSION"
  - source activate test

  - conda install orekit
  - conda install pytorch torchvision torchaudio cudatoolkit -c pytorch
  - pip install -e .[test]

script:
  - pytest --color=yes --cov=gym_satellite_trajectory --cov-report=html:./reports/coverage

after_success:
  - codecov
