os: linux

dist: xenial

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

cache: pip

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p "${HOME}/miniconda"
  - export PATH="${HOME}/miniconda/bin:${PATH}"

  - conda config --set always_yes yes
  - conda update conda
  - conda config --add channels conda-forge

install:
  - conda create -n test python="$TRAVIS_PYTHON_VERSION"
  - source activate test

  - conda install orekit=10.0

  - pip install -e .[test]

script:
  - which python  # TODO remove
  - which pytest  # TODO remove
  - python -m pytest --color=yes --cov gym_satellite_trajectory --cov-report=html:./reports/coverage

after_success:
  - codecov
